# general
################################################################################
# experiment files directory
experiment_directory: experiments

# experiment filenames prefix
filename_prefix: experiment

# PyTorch random number generator initialization seed
#random_seed: 5
#random_seed: 7
#random_seed: 11
################################################################################

# dataset
################################################################################
dataset_id: 1pct
#dataset_id: 5pct
#dataset_id: 20pct
#dataset_id: full

# training, validation, test split
test_ratio: 0.1
validation_ratio: 0.1
################################################################################

# features
################################################################################
sequence_length: 7549  # median
#sequence_length: 29001  # mean
#sequence_length: 115019  # 29001 + 86018 : mean + 1 * standard_deviation
################################################################################

# network architecture
################################################################################
# number of connections between fully connected network layers
#num_connections: 256
num_connections: 512
#num_connections: 1024
#num_connections: 2048

# max norm for gradient clipping
clip_max_norm: 5

dropout_probability: 0
#dropout_probability: 0.05
#dropout_probability: 0.1
################################################################################

# training
################################################################################
#batch_size: 128
#batch_size: 256
batch_size: 512
#batch_size: 1024
#batch_size: 2048

#num_workers: 0
num_workers: 1
#num_workers: 3

#learning_rate: 0.01
learning_rate: 0.005
#learning_rate: 0.001
#learning_rate: 0.0005
#learning_rate: 0.0001

# number of epochs without validation loss improvement before training stops
patience: 5
#patience: 7

# maximum number of training epochs
max_epochs: 1
#max_epochs: 3
#max_epochs: 10
#max_epochs: 100
#max_epochs: 1000
################################################################################
